services:
  db:
    image: postgres:15-alpine
    container_name: halal-center-db
    restart: always
    environment:
      POSTGRES_USER: halal_center
      POSTGRES_PASSWORD: root
      POSTGRES_DB: halal_center
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
