services:
  db:
    image: postgres:15-alpine
    container_name: halal-center-db
    restart: always
    environment:
      POSTGRES_USER: halal_center
      POSTGRES_PASSWORD: root
      POSTGRES_DB: halal_center
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:z

  minio:
    image: minio/minio
    container_name: halal_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      # Kita set user/pass yang gampang diingat dan PASTI
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  # 2. SERVICE NEXTJS
  # 3. APLIKASI (Next.js)
  web:
    build: .
    container_name: halal_web
    restart: always
    environment:
      DATABASE_URL: "postgresql://halal_center:root@db:5432/halal_center"
      # Config MinIO untuk Server Action (Internal Docker Network)
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "admin"
      S3_SECRET_KEY: "password123"
      S3_BUCKET_NAME: "berita"
      S3_REGION: "us-east-1"

      # --- TAMBAHAN WAJIB UNTUK AUTH ---
      # 1. URL asli website kamu (PENTING)
      NEXTAUTH_URL: "http://localhost"
      AUTH_URL: "http://localhost"

      # 2. Secret acak untuk enkripsi cookie (Wajib ada!)
      # Bisa isi acak apa saja, misal hasil ketikan keyboard
      AUTH_SECRET: "rahasia_super_kunci_gembok_pagar_rumah_123"
      NEXTAUTH_SECRET: "rahasia_super_kunci_gembok_pagar_rumah_123"

      # 3. Percayai Proxy (Karena kita pakai Docker/Nginx)
      AUTH_TRUST_HOST: "true"
    depends_on:
      - db
      - minio

  nginx:
    image: nginx:alpine
    container_name: halal_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
    ports:
      - "80:80" # Pintu Utama Laptop Kamu
    depends_on:
      - web
      - minio

volumes:
  postgres_data:
