services:
  db:
    image: postgres:15-alpine
    container_name: halal-center-db
    restart: always
    environment:
      POSTGRES_USER: halal_center
      POSTGRES_PASSWORD: root
      POSTGRES_DB: halal_center
    # Port 5432 di VPS diarahkan ke 5432 container
    # Pastikan tidak ada postgres lain yang jalan di VPS secara native
    ports:
      - "5432:5432"
    volumes:
      # Named Volume: Docker yang mengelola foldernya secara otomatis
      - postgres_data:/var/lib/postgresql/data:z

  minio:
    image: minio/minio
    container_name: halal_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      # Bind Mount: Data disimpan di folder ./minio_data di sebelah file docker-compose ini
      - ./minio_data:/data:z

  web:
    build: .
    container_name: halal_web
    restart: always
    # Port 3001 di VPS (PP Bisnis pakai 3000, jadi kita pakai 3001)
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://halal_center:root@db:5432/halal_center"
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "minioadmin" # Sesuaikan dengan MINIO_ROOT_USER
      S3_SECRET_KEY: "minioadmin" # Sesuaikan dengan MINIO_ROOT_PASSWORD
      S3_BUCKET_NAME: "berita"
      S3_REGION: "us-east-1"
      # Gunakan domain asli untuk NextAuth
      NEXTAUTH_URL: "https://lph.radenfatah.ac.id"
      NEXT_PUBLIC_MINIO_URL: "http://103.84.119.130:9000"
      AUTH_TRUST_HOST: "true"
      AUTH_SECRET: "rahasia_super_kunci_gembok_pagar_rumah_123"
    depends_on:
      - db
      - minio

  # Nginx di dalam docker ini hanya untuk internal project Halal
  # Untuk akses publik, gunakan Nginx Utama di VPS (Host) sebagai Reverse Proxy
  nginx_internal:
    image: nginx:alpine
    container_name: halal_nginx_internal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
    # Kita pindahkan portnya agar tidak bentrok dengan port 80 VPS
    ports:
      - "8081:80"
    depends_on:
      - web

volumes:
  postgres_data:
