services:
  db:
    image: postgres:15-alpine
    container_name: halal-center-db
    restart: always
    environment:
      POSTGRES_USER: halal_center
      POSTGRES_PASSWORD: root
      POSTGRES_DB: halal_center
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:z

  minio:
    image: minio/minio
    container_name: halal_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin_uin" # Ganti password yang kuat
      MINIO_ROOT_PASSWORD: "password_super_aman_uin"
    volumes:
      - ./minio_data:/data:z # Data fisik tersimpan di folder ini di VPS
    command: server /data --console-address ":9001"
    restart: always

  # 2. SERVICE NEXTJS
  # 3. APLIKASI (Next.js)
  web:
    build: .
    container_name: halal_web
    restart: always
    environment:
      DATABASE_URL: "postgresql://halal_center:root@db:5432/halal_center"
      # Config MinIO untuk Server Action (Internal Docker Network)
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "admin"
      S3_SECRET_KEY: "password123"
      S3_BUCKET_NAME: "berita"
      S3_REGION: "us-east-1"
    depends_on:
      - db
      - minio

  nginx:
    image: nginx:alpine
    container_name: halal_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
    ports:
      - "80:80" # Pintu Utama Laptop Kamu
    depends_on:
      - web
      - minio

volumes:
  postgres_data:
